# Generated by Django 4.2.4 on 2023-09-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('legend', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('fotos', models.CharField(max_length=100)),
            ],
        ),
    ]
