# Generated by Django 4.2.4 on 2023-09-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='fotos',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='fotografia',
            old_name='legend',
            new_name='legenda',
        ),
    ]
